//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public  class KMICERIKRESIM
    {
        public int ID { get; set; }
        public int ICERIKID { get; set; }
        public string ALT { get; set; }
    
        public virtual KMICERIK KMICERIK { get; set; }
    }
}
