//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public class KMICERIK
    {
        public KMICERIK()
        {
            this.KMICERIKRESIM = new HashSet<KMICERIKRESIM>();
        }
    
        public int ID { get; set; }
        public int KATID { get; set; }
        public string TRBASLIK { get; set; }
        public string TRICERIK { get; set; }
        public string TRKISAICERIK { get; set; }
        public string TRANAHTARKELIME { get; set; }
        public string ENBASLIK { get; set; }
        public string ENICERIK { get; set; }
        public string ENKISAICERIK { get; set; }
        public string ENANAHTARKELIME { get; set; }
        public string RUBASLIK { get; set; }
        public string RUICERIK { get; set; }
        public string RUKISAICERIK { get; set; }
        public string RUANAHTARKELIME { get; set; }
    
        public virtual KMKATEGORI KMKATEGORI { get; set; }
        public virtual ICollection<KMICERIKRESIM> KMICERIKRESIM { get; set; }
    }
}
