//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public  class KMKATEGORI
    {
        public KMKATEGORI()
        {
            this.KMICERIK = new HashSet<KMICERIK>();
        }
    
        public int ID { get; set; }
        public int PARENTID { get; set; }
        public string TRAD { get; set; }
        public string ENAD { get; set; }
        public string RUAD { get; set; }
        public int SIRA { get; set; }
        public string URL { get; set; }
        public bool YENIPENCERE { get; set; }
    
        public virtual ICollection<KMICERIK> KMICERIK { get; set; }
    }
}
