//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public  class TBLAPLIKASYON
    {
        public int ID { get; set; }
        public string JANTKODU { get; set; }
        public string APPNO { get; set; }
        public string BRAND { get; set; }
        public string TYPE { get; set; }
        public string MODEL { get; set; }
        public string PCD { get; set; }
        public string ET { get; set; }
        public string RING_CODE { get; set; }
        public string BOLT_CODE { get; set; }
        public string KIT_CODE { get; set; }
        public string WEIGHT { get; set; }
        public string SIZE { get; set; }
    }
}
