//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public class TBLBANNER
    {
        public int BANNERID { get; set; }
        public Nullable<int> JANTMASID { get; set; }
        public Nullable<int> SIRA { get; set; }
        public string ICERIK { get; set; }
    
        public virtual TBLJANTMAS TBLJANTMAS { get; set; }
    }
}
