//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public  class TBLBAYILERLAS
    {
        public int BAYIID { get; set; }
        public string ADI { get; set; }
        public string ADRESI { get; set; }
        public string TEL { get; set; }
        public string TEL2 { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string WEB { get; set; }
        public string GBASLIK { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public Nullable<int> ILCEID { get; set; }
        public Nullable<double> LATITUDE { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
        public string GMAP { get; set; }
    
        public virtual TBLILCELER TBLILCELER { get; set; }
    }
}
