//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public  class TBLILLER
    {
        public TBLILLER()
        {
            this.TBLILCELER = new HashSet<TBLILCELER>();
        }
    
        public int ilID { get; set; }
        public string ilAd { get; set; }
        public Nullable<double> LATITUDE { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
    
        public virtual ICollection<TBLILCELER> TBLILCELER { get; set; }
    }
}
