//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public  class TBLJANTMAS
    {
        public TBLJANTMAS()
        {
            this.TBLBANNER = new HashSet<TBLBANNER>();
            this.TBLJANTRESIMIL = new HashSet<TBLJANTRESIMIL>();
            this.TBLJANTTRA = new HashSet<TBLJANTTRA>();
            this.TBLMULTIMEDYA = new HashSet<TBLMULTIMEDYA>();
        }
    
        public int JANTMASID { get; set; }
        public string JANTADI { get; set; }
        public Nullable<int> SIRANO { get; set; }
        public Nullable<bool> YENI { get; set; }
        public string ACIKLAMA { get; set; }
        public string ACIKLAMAEN { get; set; }
        public string ACIKLAMADE { get; set; }
        public string ACIKLAMARU { get; set; }
        public Nullable<int> GRUPID { get; set; }
        public Nullable<bool> AKTIF { get; set; }
        public string RESIMLRLINK { get; set; }
        public string RESIMHRLINK { get; set; }
        public string SATINALLINK { get; set; }
        public string SERTIFIKALINK { get; set; }
        public string VIDEOLINK { get; set; }
    
        public virtual ICollection<TBLBANNER> TBLBANNER { get; set; }
        public virtual TBLJANTGRUP TBLJANTGRUP { get; set; }
        public virtual ICollection<TBLJANTRESIMIL> TBLJANTRESIMIL { get; set; }
        public virtual ICollection<TBLJANTTRA> TBLJANTTRA { get; set; }
        public virtual ICollection<TBLMULTIMEDYA> TBLMULTIMEDYA { get; set; }
    }
}
