//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public  class TBLJANTRENKIL
    {
        public int JANTRENKID { get; set; }
        public Nullable<int> JANTTRAID { get; set; }
        public Nullable<int> RENKID { get; set; }
        public string ACIKLAMA { get; set; }
        public string ACIKLAMAEN { get; set; }
        public string ACIKLAMADE { get; set; }
        public string ACIKLAMARU { get; set; }
    
        public virtual TBLJANTRENK TBLJANTRENK { get; set; }
        public virtual TBLJANTTRA TBLJANTTRA { get; set; }
    }
}
