//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public  class TBLJANTPCD
    {
        public TBLJANTPCD()
        {
            this.TBLJANTPCDIL = new HashSet<TBLJANTPCDIL>();
        }
    
        public int PCDID { get; set; }
        public string PCDADI { get; set; }
    
        public virtual ICollection<TBLJANTPCDIL> TBLJANTPCDIL { get; set; }
    }
}
