//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public  class TBLJANTRESIM
    {
        public TBLJANTRESIM()
        {
            this.TBLJANTRESIMIL = new HashSet<TBLJANTRESIMIL>();
        }
    
        public int RESIMID { get; set; }
        public Nullable<int> RENKID { get; set; }
        public Nullable<bool> VITRIN { get; set; }
        public Nullable<int> RESIMTUR { get; set; }
        public Nullable<int> BIJONSAY { get; set; }
    
        public virtual TBLJANTRENK TBLJANTRENK { get; set; }
        public virtual ICollection<TBLJANTRESIMIL> TBLJANTRESIMIL { get; set; }
    }
}
