//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public  class TBLJANTRENK
    {
        public TBLJANTRENK()
        {
            this.TBLJANTRENKIL = new HashSet<TBLJANTRENKIL>();
            this.TBLJANTRESIM = new HashSet<TBLJANTRESIM>();
        }
    
        public int RENKID { get; set; }
        public string RENKADI { get; set; }
        public string RENKKODU { get; set; }
    
        public virtual ICollection<TBLJANTRENKIL> TBLJANTRENKIL { get; set; }
        public virtual ICollection<TBLJANTRESIM> TBLJANTRESIM { get; set; }
    }
}
