//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public  class TBLJANTGRUP
    {
        public TBLJANTGRUP()
        {
            this.TBLJANTMAS = new HashSet<TBLJANTMAS>();
        }
    
        public int GRUPID { get; set; }
        public string GRUPAD { get; set; }
    
        public virtual ICollection<TBLJANTMAS> TBLJANTMAS { get; set; }
    }
}
