//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public  class TBLJANTTRA
    {
        public TBLJANTTRA()
        {
            this.TBLJANTPCDIL = new HashSet<TBLJANTPCDIL>();
            this.TBLJANTRENKIL = new HashSet<TBLJANTRENKIL>();
        }
    
        public int JANTTRAID { get; set; }
        public Nullable<int> JANTMASID { get; set; }
        public string JANTKODU { get; set; }
        public Nullable<int> EBATID { get; set; }
        public Nullable<bool> YENI { get; set; }
        public Nullable<int> SIRA { get; set; }
        public string ACIKLAMA { get; set; }
        public string ACIKLAMAEN { get; set; }
        public string ACIKLAMADE { get; set; }
        public string ACIKLAMARU { get; set; }
        public string UYUMLUARACLAR { get; set; }
    
        public virtual TBLJANTEBAT TBLJANTEBAT { get; set; }
        public virtual TBLJANTMAS TBLJANTMAS { get; set; }
        public virtual ICollection<TBLJANTPCDIL> TBLJANTPCDIL { get; set; }
        public virtual ICollection<TBLJANTRENKIL> TBLJANTRENKIL { get; set; }
    }
}
