//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public  class TBLJANTEBATIL
    {
        public int JANTEBATID { get; set; }
        public Nullable<int> JANTTRAID { get; set; }
        public Nullable<int> EBATID { get; set; }
    }
}
