//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public  class TBLKISABILGILAS
    {
        public int KBID { get; set; }
        public string BASLIK { get; set; }
        public string ICERIK { get; set; }
        public Nullable<System.Guid> RESIM { get; set; }
        public Nullable<int> GRUPID { get; set; }
        public string GRUPADI { get; set; }
        public Nullable<int> BAGLA { get; set; }
        public Nullable<bool> FOTYAYINLA { get; set; }
        public string EKALAN { get; set; }
        public System.DateTime TARIH { get; set; }
    }
}
