//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public  class TBLLASTIKEBAT
    {
        public int ID { get; set; }
        public string STOKKODU { get; set; }
        public Nullable<int> URUNID { get; set; }
        public string EBAT { get; set; }
        public string EBATJANT { get; set; }
    
        public virtual TBLURUNLAS TBLURUNLAS { get; set; }
    }
}
