//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public  class TBLURUNGRUPLAS
    {
        public TBLURUNGRUPLAS()
        {
            this.TBLURUNLAS = new HashSet<TBLURUNLAS>();
        }
    
        public int GRUPID { get; set; }
        public string GRUPAD { get; set; }
        public string URL { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public Nullable<int> SIRA { get; set; }
        public Nullable<bool> GRUPAKTIF { get; set; }
        public Nullable<bool> MENUAKTIF { get; set; }
        public Nullable<System.Guid> RESIM { get; set; }
    
        public virtual ICollection<TBLURUNLAS> TBLURUNLAS { get; set; }
    }
}
