//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kormetal.Entities.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public  class TBLURUNLAS
    {
        public TBLURUNLAS()
        {
            this.TBLLASTIKEBAT = new HashSet<TBLLASTIKEBAT>();
            this.TBLLASTIKOZELLIK = new HashSet<TBLLASTIKOZELLIK>();
            this.TBLLINKLER = new HashSet<TBLLINKLER>();
        }
    
        public int URUNID { get; set; }
        public string URUNADI { get; set; }
        public string URUNKODU { get; set; }
        public Nullable<int> URUNGRUPID { get; set; }
        public Nullable<double> URUNFIYAT { get; set; }
        public Nullable<System.Guid> URUNRESIM { get; set; }
        public string URUNAYRINTI { get; set; }
        public Nullable<bool> YENI { get; set; }
        public Nullable<int> SIRA { get; set; }
        public string MEVSIM { get; set; }
        public string KISATANITIM { get; set; }
        public string RESIMADRES { get; set; }
        public string URUNEKALAN { get; set; }
        public string URUNKATEGORI { get; set; }
        public Nullable<bool> DSI { get; set; }
        public Nullable<bool> YAKINDA { get; set; }
        public string SLOGAN { get; set; }
    
        public virtual ICollection<TBLLASTIKEBAT> TBLLASTIKEBAT { get; set; }
        public virtual ICollection<TBLLASTIKOZELLIK> TBLLASTIKOZELLIK { get; set; }
        public virtual ICollection<TBLLINKLER> TBLLINKLER { get; set; }
        public virtual TBLURUNGRUPLAS TBLURUNGRUPLAS { get; set; }
    }
}
